# Generated by Django 4.2.25 on 2025-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('next_index', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVEHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=200)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cve_id'], name='cve_records_cve_id_e9b96b_idx')],
            },
        ),
    ]
