# Generated by Django 4.2.25 on 2025-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cvehistory',
            name='cve_records_cve_id_e9b96b_idx',
        ),
        migrations.RenameField(
            model_name='cvehistory',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='cvehistory',
            old_name='cve_id',
            new_name='cveId',
        ),
        migrations.RenameField(
            model_name='cvehistory',
            old_name='action',
            new_name='eventName',
        ),
        migrations.RemoveField(
            model_name='cvehistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cvehistory',
            name='raw',
        ),
        migrations.AddField(
            model_name='cvehistory',
            name='cveChangeId',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvehistory',
            name='sourceIdentifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='cvehistory',
            index=models.Index(fields=['cveId'], name='cve_records_cveId_91ca02_idx'),
        ),
        migrations.AddIndex(
            model_name='cvehistory',
            index=models.Index(fields=['cveChangeId'], name='cve_records_cveChan_0560eb_idx'),
        ),
    ]
